hand_tracker/urls.py
"""hand_tracker URL Configuration
"""

from django.urls import path

from app.views import *

urlpatterns = [
    path('', home, name='home'),
    path('student/', student_join, name='student'),
    path('student/class', class_run_student, name='student-class'),
    path('professor/', professor_create, name='professor'),
    path('professor/class', class_run_professor, name='professor-class'),
    path('professor/class/report', class_report, name='report'),
]

app/models.py
"""
Defines the object / DB models.
"""
from django.db import models


class ClassRoom(models.Model):
    """
    Manages the running classroom. :TODO: add the delete method.
    """
    class_number = models.IntegerField()
    professor_name = models.TextField(max_length=30)
    professor_email = models.EmailField()
    class_running = models.BooleanField(default=True)

    def __str__(self):
        return self.class_number

    @property
    def is_running(self):
        return self.class_running

    @property
    def group_name(self):
        return "room-%s" % self.class_number


class Student(models.Model):
    """
    The student model.
    """
    student_name = models.TextField(max_length=30)
    acknowledged = models.IntegerField(default=0)
    modifier = models.FloatField()
    class_room = models.ForeignKey(ClassRoom,
                                   on_delete=models.CASCADE)
    hand = models.BooleanField(default=False)

    def __str__(self):
        """
        Overrides default str method to return student_name.
        :return: student_name
        """
        return self.student_name

    def acknowledge(self):
        """
        Acknowledging a student automatically reduces all other student
        modifiers by 10%.
        :return: Nothing.
        """
        other_students = Student.objects.filter(class_room=self.class_room)

        for student in other_students:
            student.modifier = student.modifier * 0.9
            student.save()

        self.acknowledged += 1
        self.modifier = 1
        self.save()

app/forms.py
import random

from django import forms
from django.utils.translation import ugettext_lazy as _

from app.models import *


class StudentJoinForm(forms.ModelForm):
    class_number = forms.IntegerField(widget=forms.NumberInput(attrs={
        'class': 'form-control',
        'placeholder': 'i.e. 000000',
    }))

    class Meta:
        model = Student
        fields = ['student_name']
        labels = ({'student_name': _('Your name.')})
        widgets = {
            'student_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'i.e. Becky Smith'
            })
        }


class ClassCreationForm(forms.ModelForm):

    class Meta:
        model = ClassRoom

        fields = ['professor_name', 'professor_email', 'class_number']
        labels = ({'professor_name': _('Your name.'),
                   'professor_email': _('Your email.')})
        widgets = {
            'professor_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'i.e. Dr. George Wallace III',
            }),
            'professor_email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'i.e. georgito@harvard.edu',
            })
        }

templates/classroom-professor.html
{% extends 'layout.html' %}

{% block content %}
    <!--suppress ALL, JSUnfilteredForInLoop, JSUnusedLocalSymbols -->
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-centered">
                <h4 class="display-4">{{ title }}</h4>
                <hr style="border-color: black"/>
                <p class="lead">Class Number: {{ class_number }}</p>
                <p>
                    <button class="btn btn-primary" onclick="clearTable()">Clear Hands</button>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-11 col-centered">
                <table id="class" class="table table-bordered" cellspacing="0" width="100%">
                </table>
                <p class="mt-3" style="text-align: right">
                    <a href="class/report?class_id={{ class_number }}">
                        <button class="btn btn-danger">End Class &raquo;</button>
                    </a>
                </p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-10 col-centered mt-3">
                <p>
                    <strong>Note:</strong> Lower scores represent how long it's been since a student was last
                    acknowledged. A score of 1.0 represents the last speaker, a score of 0.0 represents a student who
                    hasn't yet spoken or hasn't spoken for long enough for their score to return to 0.0. Each time a
                    student is acknowledged all other students have their scores reduced by 10%.
                </p>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <!--suppress JSUnresolvedLibraryURL -->
    <script src="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.js"
            integrity="sha384-8g8uXcdgZXxmVzS9bPo9WebRt8GduLrBhtaimcGKQJDTZzt1gZM2K/qsHQ2ShwND"
            crossorigin="anonymous"></script>
    <script>
        {# mmmm... reconnecting websocket.... #}
        var socket = new ReconnectingWebSocket("wss://joshharkema.com:8001/websocket/");

        {# Stores the table data (empty upon initial instantiation). #}
        var dataSet = [];

        {# Draw the empty table for first run. #}
        var table = $('#class').DataTable({
            bFilter: false,
            bInfo: false,
            bPaginate: false,
            data: dataSet,
            columns: [
                {title: "Name"},
                {title: "Score"},
                {title: ""}
            ]
        });

        {# Clear the table, function initiates a reset of all the student's hand states. #}

        function clearTable() {
            dataSet = [];

            {# Kill the table. #}
            table.destroy();

            {# Send the reset command. #}
            socket.send(JSON.stringify({
                "command": "clear-hands",
                "class_id": "{{ class_number }}"
            }));

            {# I wish there was a way I could do it without wiping the table every time, but there isn't. Well, beyond #}
            {# recoding the whole thing to use AJAX instead of websockets... #}
            table = $('#class').DataTable({
                bFilter: false,
                bInfo: false,
                bPaginate: false,
                data: dataSet,
                columns: [
                    {title: "Name"},
                    {title: "Score"},
                    {title: ""}
                ]
            });
        }

        {# Acknowledge a student. #}

        function acknowledge(student) {
            student = String(student);
            socket.send(JSON.stringify({
                "command": "acknowledge",
                "class_id": "{{ class_number }}",
                "student_name": student
            }));

        }

        {# Connect to the class after opening socket. #}
        socket.onopen = function (ev) {
            console.log("Connection to websocket opened.");
            socket.send(JSON.stringify({
                "command": "join-prof",
                "class_id": "{{ class_number }}"
            }));
        };

        {# Deal with the incoming messages. #}
        socket.onmessage = function (message) {
            console.log("Got websocket message " + message.data);

            {# Parse the data into a JSON object. #}
            var data = JSON.parse(message.data);

            {# Alert any errors. #}
            if (data.error) {
                alert(data.error);
                return;
            }

            {# Redraw the table everytime event type 2 happen. #}
            if (data["msg_type"] === 2) {
                table.destroy();
                dataSet = [];

                for (var key in data["user_list"]) {

                    {# Create the HTML for the button links. #}
                    var link_text = String("<button class='btn button-primary' onclick='acknowledge(" +
                        data["user_list"][key][1] + ")'><span class=\"oi oi-check\"></span></button>");

                    {# Push the data into the dataSet #}
                    dataSet.push([key, data["user_list"][key][0], link_text]);
                }

                {# Instantiate new table. #}
                table = $('#class').DataTable({
                    bFilter: false,
                    bInfo: false,
                    bPaginate: false,
                    data: dataSet,
                    columns: [
                        {title: "Name"},
                        {title: "Score"},
                        {title: ""}
                    ]
                });

                {# Draw the table. #}
                table.draw();
            }
        }
    </script>
{% endblock %}

templates/classroom-report.html
{% extends 'layout.html' %}

{% block content %}
    <!--suppress ALL -->
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-10 col-centered">
                <h4 class="display-4">{{ title }}</h4>
                <hr style="border-color: black"/>
                <p class="lead">Report for Class Number: {{ class_number }}</p>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-11 col-centered">
                <table id="report" class="table table-bordered" cellspacing="0" width="100%">
                </table>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <!--suppress JSUnresolvedLibraryURL -->
    <script src="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.js"
            integrity="sha384-8g8uXcdgZXxmVzS9bPo9WebRt8GduLrBhtaimcGKQJDTZzt1gZM2K/qsHQ2ShwND"
            crossorigin="anonymous"></script>

    <script>
        {# Draw the table #}
        $(document).ready(function () {
            $('#report').DataTable({
                bFilter: false,
                bInfo: false,
                bPaginate: false,
                data: {{ report_data | safe }},
                columns: [
                    {title: "Name"},
                    {title: "Acknowledgments"}
                ]
            });
        })
    </script>

{% endblock %}

templates/classroom-student.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6 justify-content-center">
                <h4 class="display-4">{{ title }}</h4>
                <hr style="border-color: black"/>
                <p style="text-align: center">
                    <button onclick="raiseHand()" class="btn btn-primary btn-lg mt-3">Raise Hand</button>
                </p>
                <p style="text-align: center">
                    <button onclick="lowerHand()" class="btn btn-primary btn-lg">Lower Hand</button>
                </p>
            </div>
        </div>

        {# Modal content is hidden on pageload, pops when wss event happens. #}
        <div class="modal fade" id="handsDown" tabindex="-1" role="dialog" aria-labelledby="handsDown"
             aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="handsDown">New Topic</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        The professor has lowered everyone's hand, discussion begins anew!
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        {# mmmm... reconnecting websocket.... #}
        var socket = new ReconnectingWebSocket("wss://joshharkema.com:8001/websocket/");

        {# Join the class. #}
        socket.onopen = function () {
            socket.send(JSON.stringify({
                "command": "join",
                "class_id": "{{ class_number }}",
                "student_name": "{{ student_name }}"
            }));
            console.log("Sending string.")
        };

        {# Deal with incoming messages. #}
        socket.onmessage = function (message) {
            console.log("Got websocket message " + message.data);

            var data = JSON.parse(message.data);

            {# Alert errors. #}
            if (data.error) {
                alert(data.error);
                return;
            }

            {# Pop snazzy modal when the topic is reset. #}
            if (data["msg_type"] === 1) {
                $('#handsDown').modal()
            }
        };

        {# Raise your hand. #}

        function raiseHand() {
            console.log({{ student_id }});
            socket.send(JSON.stringify({
                "command": "raise",
                "class_id": "{{ class_number }}",
                "student_name": "{{ student_id }}"
            }))
        }

        {# Lower your hand. #}

        function lowerHand() {
            socket.send(JSON.stringify({
                "command": "lower",
                "class_id": "{{ class_number }}",
                "student_name": "{{ student_id }}"
            }))
        }

    </script>
{% endblock %}

templates/index.html
{% extends 'layout.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-lg-12 col-centered">
                <h4 class="display-4">{{ title }}</h4>
                <hr style="border-color: black"/>
                <p class="lead">
                    This webapp can be used to track contributions in a classroom environment. No personal information
                    is stored--when a professor ends a class, all student names and info are purged from the database.
                    This webapp is totally free for anyone to use, no accounts are needed, no signup, just create a
                    class and start tracking!
                </p>
                <br/>
                <p style="text-align: center;"><a href="student/">
                    <button class="btn btn-lg btn-primary">Join a Class &raquo;</button>
                </a></p>
                <p style="text-align: center;"><a href="professor/">
                    <button class="btn btn-lg btn-primary">Create a Class &raquo;</button>
                </a></p>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}

{% endblock %}

templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content=""/>
    <meta name="author" content="Josh Harkema">

    <title>{{ title }} - Hand Tracker</title>

    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/open-iconic/1.1.1/font/css/open-iconic-bootstrap.min.css"
          integrity="sha256-BJ/G+e+y7bQdrYkS2RBTyNfBHpA9IuGaPmf9htub5MQ=" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://joshharkema.com/static/css/site.min.css"
          integrity="sha384-jv00OPN0JrnfIi4kD9dBOnoXw75sO/jp7M3EKXBDc4nXqhObJEm3XtXZ0fp+Gji7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/v/bs4/dt-1.10.16/datatables.min.css"
          integrity="sha384-IuzzZskbeTpsEsReJBMMQ1jX5gSBpD1bsB1Tsj6+LkjOgDORA3IggERNe0l4A0jc" crossorigin="anonymous">

</head>

<body>

<nav class="navbar fixed-top navbar-expand-md navbar-dark bg-primary mb-4">
    <a class="navbar-brand" href="/">Hand Tracker</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="oi oi-menu"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {% if request.resolver_match.url_name == "home" %}active{% endif %}">
                <a class="nav-link" href="/">Home{% if request.resolver_match.url_name == "home" %}
                    <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == "student" %}active{% endif %}">
                <a class="nav-link" href="/student">Join Class{% if request.resolver_match.url_name == "student" %}
                    <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
            <li class="nav-item {% if request.resolver_match.url_name == "professor" %}active{% endif %}">
                <a class="nav-link" href="/professor">Create Class
                    {% if request.resolver_match.url_name == "professor" %}
                        <span class="sr-only">(current)</span>{% endif %}</a>
            </li>
        </ul>
    </div>
</nav>
<main role="main" class="container">

    {# Display the Header   #}
    {% if request.resolver_match.url_name != "home" %}
        <div class="container-fluid">
            {# put the page title here if needed #}
        </div>
    {% endif %}

    {# Display any messages   #}
    {% if messages %}
        {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>
                <a class="close" data-dismiss="alert" href="#">&times;</a>
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {# Insert content block   #}
    {% block content %}{% endblock %}

    <hr class="my-4" style="border-color: white"/>

    <footer>
        <p style="text-align: center">&copy; {{ year }} - Josh Harkema - <strong>Licensed under CC-BY-SA 2.5</strong> -
            <a href="https://creativecommons.org/licenses/by-sa/2.5/ca/">
                https://creativecommons.org/licenses/by-sa/2.5/ca/</a></p>
        <p style="text-align: center">Use of this project is AT YOUR OWN RISK it is still undergoing
            bug fixing and testing.</p>
    </footer>

</main>
<!--suppress JSUnresolvedLibraryURL -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<!--suppress JSUnresolvedLibraryURL -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<!--suppress JSUnresolvedLibraryURL -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<!--suppress JSUnresolvedLibraryURL -->
<script src="https://joshharkema.com/static/js/reconnecting-websocket.min.js"
        integrity="sha384-FtJyC+/3fgtPbqlacLHdGwBrmPjKoYBsiqNF5/BEprsnIXB4xtXLCJRx7Xx+TWKP"
        crossorigin="anonymous"></script>
{% block scripts %}{% endblock %}

</body>
</html>

templates/professor.html
{% extends "layout.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6 col-centered">
                <form action="class" method="post" class="form-horizontal">
                    <h4 class="display-4">{{ title }}</h4>
                    <hr style="border-color: black"/>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_student_name" class="control-label">Your full name: </label>
                        {{ form.professor_name }}
                    </div>
                    <div class="form-group">
                        <label for="id_class_number" class="control-label">Your email: </label>
                        {{ form.professor_email }}
                    </div>
                    <div class="form-group">
                        <input type="hidden" name="class_number" value="{{ class_number }}"/>
                        <input type="submit" value="Create Class &raquo;" class="btn btn-primary mt-2"/>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}

templates/student.html
{% extends "layout.html" %}

{% block content %}
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-6 col-centered">
                <form action="class" method="post" class="form-horizontal">
                    <h4 class="display-4">{{ title }}</h4>
                    <hr style="border-color: black"/>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_student_name" class="control-label">Your full name: </label>
                        {{ form.student_name }}
                    </div>
                    <div class="form-group">
                        <label for="id_class_number" class="control-label">Class Number: </label>
                        {{ form.class_number }}
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Join Class &raquo;" class="btn btn-primary mt-2"/>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}

{% endblock %}